### ISSUE TITLE
Possible conflict with steamdeck update

### ISSUE THREAD

**Issue by isighless** [primetime00/memory_hack#1]
I installed this a few days ago to give me an edge against a tough boss.  I installed it as a service.  I had to set the sudo password to install it.

Last night, my steamdeck said there was an update, so I updated.  After the update, the screen doesn't come on.  I can hear a beep, and the fan, and the haptics of the touchpads seem to respond, but the screen stays black.

It's likely the error is unrelated to this app, but I figured I'd mention it here just in case.

**Comment by primetime00** [comment]
Thanks for letting me know.  I'm not sure that this app would cause that kind of issue.  I might also have the update to install, so I will try as well while the app is installed.  Are you using a phone to interface with memory_hack?  If so, can you still bring up the app on the phone while the deck is on but blacked out?

**Comment by isighless** [comment]
The web interface doesn't load.

**Comment by primetime00** [comment]
It could be that the app isn't loading during boot.  You might try a hard
reboot to see if it works.  If not, you may have to roll back the update.
I've not had to do that yet.

**Comment by isighless** [comment]
Hard reboot doesn't seem to have an effect.  I've tried suggestions from all over the internet, and nothing seems to have had any effect.  Maybe it would be better for you not to do the update on your steamdeck.  I wouldn't want yours bricked as well.

**Comment by primetime00** [comment]
Thanks, I updated and rebooted anyway.  I'm mainly developing for the SD anyway so I want to make sure everything works correctly.  Anyway, after my update everything seems smooth.  I even shutdown and powered back on.  Other than my app, I don't have other non-game apps installed, so I'm not sure if it could be something else.

**Comment by isighless** [comment]
Well, I appreciate you checking.  Most likely that means it's not your app that was my issue.  I'm about to try to do a factory reset. 
 Hopefully the screen turns on for the bootloader.
